name: Render PROJECTS

on:
  push:
    paths:
      - 'projects.toml'
      - 'render.py'
      - '.github/workflows/python-render.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install pandas tabulate
    - name: Render projects
      run: |
        python render.py
